import asyncio
import os
import re
import json
import requests
from typing import Union

import yt_dlp
from pyrogram.enums import MessageEntityType
from pyrogram.types import Message
from youtubesearchpython.__future__ import VideosSearch

from maythusharmusic.utils.database import is_on_off
from maythusharmusic.utils.formatters import time_to_seconds

# --- Cookies Configuration Start ---
COOKIES_DICT = {
    'SID': 'g.a0007AjBDAGf8qAf8ERi-oeurSDXyUxxZCHMNvy2ZSgtD5VlaD3e_WaoFfWdY19qEqg5Jm4QZgACgYKATISARESFQHGX2MiEciM95_oWLKqQXxYbTa7tBoVAUF8yKrN_qMlO8vGsch2lCLeRY9E0076',
    '__Secure-1PSIDTS': 'sidts-CjUBBj1CYgZ3o_MdTmhFnFpd67mzEtcGWZK06ddJ4ml9DB_1zP4TfQs-RbG5N2K2uUPh57NCHhAA',
    '__Secure-3PSIDTS': 'sidts-CjUBBj1CYgZ3o_MdTmhFnFpd67mzEtcGWZK06ddJ4ml9DB_1zP4TfQs-RbG5N2K2uUPh57NCHhAA',
    '__Secure-1PSID': 'g.a0007AjBDAGf8qAf8ERi-oeurSDXyUxxZCHMNvy2ZSgtD5VlaD3ecmZi4LEU5zy3mS_QH6O64QACgYKAUASARESFQHGX2MiQTrVUArmX53Xh2ba-yZWxhoVAUF8yKpzAvOmtuMUMm08mRmrxppe0076',
    '__Secure-3PSID': 'g.a0007AjBDAGf8qAf8ERi-oeurSDXyUxxZCHMNvy2ZSgtD5VlaD3eB8_M5UflZBEYLfJ1jzLSqAACgYKAboSARESFQHGX2MihTDO466QXONdQDTTizLRjhoVAUF8yKqksk8-NwOazJh6cGIJ73ND0076',
    'HSID': 'AU2j7XssiG1fbZVxr',
    'SSID': 'An85p3JUHaUlafv9G',
    'APISID': 'I85SSveKd7psklRn/A3G-mamolPTLNJ-YM',
    'SAPISID': 'TofN2OmMgjyyZITV/Aq2uluC-GnfgSbGKQ',
    '__Secure-1PAPISID': 'TofN2OmMgjyyZITV/Aq2uluC-GnfgSbGKQ',
    '__Secure-3PAPISID': 'TofN2OmMgjyyZITV/Aq2uluC-GnfgSbGKQ',
    'LOGIN_INFO': 'AFmmF2swRQIgS-5T5Vg_ImC3TqWSmGE43mzvYAhTFfkc9HgRLj7IlJsCIQDSoIleAjSMHUBdctq0ER_rcPIsyEolXC4RDgniwmLjFQ:QUQ3MjNmeUQxemZuVnBiSmw4UFktU0VCb2U1MDV0TlB2RzJaVWw5RGt6anNiNmtFSjlseUNnT3JGR044cHpPQkJBSVNUZGx0Ukd0bEkteUNzQUVGbFFvbEJnYnRrV0lmZU9NVFdlMHRnY2QybG5RcXZnamRjQjRLeDdXN3FlM3NuTUpDV1RiV2VEYm01ZExYb3lra29KQkl2RFZXaU03NDBR',
    '__Secure-YNID': '16.YT=eFQbKQcm5x8WsNDVu7QUnsXhZrPyScXcpNj3opxbvqvA_CKcJXkw53jKziUiYtYxpayF3dzBNRqPJRP2CMZuHYHxQNWsnweJixmY3Wq8E_52C1rPDglzdbRms9IK9AOG6akpdv-gUy0WuHWWoVRa6CDGDQJtq6ZUz5NXaOdgkgR29wT6U8rq-3T4YcvsQ8v8ZxfOkozZEiSB8coG_No8Thy49Gxn6pfKlkLvz2Vo07V7VwFO6KJrwVmuwBIVbYV0OWC3jmkCY7KiYTZvtkeHU9-KimpK2k-JufL7ZTB8XfaXK4peYY63dJY4tQxhSbnKkCsa-lPhUePGRkaC89YuBg',
    'YSC': 'jeDjLR10G4w',
    '__Secure-ROLLOUT_TOKEN': 'CKiXuMHe7Y7uPRDqvJOd8YiTAxjqvJOd8YiTAw%3D%3D',
    'VISITOR_INFO1_LIVE': 'GJOnN-EO4iQ',
    'VISITOR_PRIVACY_METADATA': 'CgJNTRIEGgAgUw%3D%3D',
    'PREF': 'tz=Asia.Rangoon',
    'SIDCC': 'AKEyXzWQSsxRxvCj8P6tdJMhOsnTvtYggU4meOVuDQy0dvZT193v_rxEGyY94PnPFPiS2sqR',
    '__Secure-1PSIDCC': 'AKEyXzUxNGYcg6PT46lE11puYtWlJhiXrNdaSOusjDNz1JKYkyaBPGSw_2McJnVw6-RLetg1FQ',
    '__Secure-3PSIDCC': 'AKEyXzWa5KIPa3NyyoCasEbuJEYzlWHM8OptB2_59euH9U6-6db-A7odgZGLm2suV0e89oRL',
}

def create_cookies_file():
    content = "# Netscape HTTP Cookie File\n"
    content += "# This file is generated by maythusharmusic Bot\n\n"
    for key, value in COOKIES_DICT.items():
        content += f".youtube.com\tTRUE\t/\tTRUE\t2147483647\t{key}\t{value}\n"
        content += f".google.com\tTRUE\t/\tTRUE\t2147483647\t{key}\t{value}\n"
    with open("cookies.txt", "w") as f:
        f.write(content)

if not os.path.exists("cookies.txt"):
    create_cookies_file()
else:
    create_cookies_file()
# --- Cookies Configuration End ---

async def shell_cmd(cmd):
    proc = await asyncio.create_subprocess_shell(
        cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    out, errorz = await proc.communicate()
    if errorz:
        if "unavailable videos are hidden" in (errorz.decode("utf-8")).lower():
            return out.decode("utf-8")
        else:
            return errorz.decode("utf-8")
    return out.decode("utf-8")

class YouTubeAPI:
    def __init__(self):
        self.base = "https://www.youtube.com/watch?v="
        self.regex = r"(?:youtube\.com|youtu\.be)"
        self.status = "https://www.youtube.com/oembed?url="
        self.listbase = "https://youtube.com/playlist?list="
        self.reg = re.compile(r"\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])")
        self.cookie_path = "cookies.txt"

    async def exists(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if re.search(self.regex, link):
            return True
        else:
            return False

    async def url(self, message_1: Message) -> Union[str, None]:
        messages = [message_1]
        if message_1.reply_to_message:
            messages.append(message_1.reply_to_message)
        text = ""
        offset = None
        length = None
        for message in messages:
            if offset:
                break
            if message.entities:
                for entity in message.entities:
                    if entity.type == MessageEntityType.URL:
                        text = message.text or message.caption
                        offset, length = entity.offset, entity.length
                        break
            elif message.caption_entities:
                for entity in message.caption_entities:
                    if entity.type == MessageEntityType.TEXT_LINK:
                        return entity.url
        if offset in (None,):
            return None
        return text[offset : offset + length]

    async def suggestion(self, link: str):
        loop = asyncio.get_running_loop()
        def fetch_suggestions():
            try:
                url = "https://suggestqueries-clients6.youtube.com/complete/search"
                params = {"client": "firefox", "ds": "yt", "q": link, "hl": "en", "gl": "US"}
                headers = {"User-Agent": "Mozilla/5.0"}
                response = requests.get(url, params=params, headers=headers)
                data = response.json()
                if data and len(data) > 1:
                    return data[1]
                return []
            except Exception:
                return []
        return await loop.run_in_executor(None, fetch_suggestions)

    async def get_recommendations(self, videoid: str):
        try:
            mix_url = f"https://www.youtube.com/watch?v={videoid}&list=RD{videoid}"
            cmd = f"yt-dlp --cookies {self.cookie_path} --get-id --flat-playlist --playlist-end 5 --skip-download {mix_url}"
            result = await shell_cmd(cmd)
            video_ids = result.strip().split("\n")
            recommendations = [vid for vid in video_ids if vid != videoid and vid != ""]
            if recommendations:
                return recommendations[0]
            return None
        except Exception:
            return None

    async def details(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
            duration_min = result["duration"]
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
            vidid = result["id"]
            if str(duration_min) == "None":
                duration_sec = 0
            else:
                duration_sec = int(time_to_seconds(duration_min))
        return title, duration_min, duration_sec, thumbnail, vidid

    async def title(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
        return title

    async def duration(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            duration = result["duration"]
        return duration

    async def thumbnail(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
        return thumbnail

    async def video(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        # Video Info only - not used for streaming anymore
        cmd = f"yt-dlp --cookies {self.cookie_path} -g -f best[height<=?720][width<=?1280] {link}"
        proc = await asyncio.create_subprocess_shell(
            cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        if stdout:
            return 1, stdout.decode().split("\n")[0]
        else:
            return 0, stderr.decode()

    async def playlist(self, link, limit, user_id, videoid: Union[bool, str] = None):
        if videoid:
            link = self.listbase + link
        if "&" in link:
            link = link.split("&")[0]
        cmd = f"yt-dlp --cookies {self.cookie_path} -i --get-id --flat-playlist --playlist-end {limit} --skip-download {link}"
        playlist = await shell_cmd(cmd)
        try:
            result = playlist.split("\n")
            for key in result:
                if key == "":
                    result.remove(key)
        except:
            result = []
        return result

    async def track(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        results = VideosSearch(link, limit=1)
        for result in (await results.next())["result"]:
            title = result["title"]
            duration_min = result["duration"]
            vidid = result["id"]
            yturl = result["link"]
            thumbnail = result["thumbnails"][0]["url"].split("?")[0]
        track_details = {
            "title": title,
            "link": yturl,
            "vidid": vidid,
            "duration_min": duration_min,
            "thumb": thumbnail,
        }
        return track_details, vidid

    async def formats(self, link: str, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        ytdl_opts = {"quiet": True, "cookiefile": self.cookie_path}
        ydl = yt_dlp.YoutubeDL(ytdl_opts)
        with ydl:
            formats_available = []
            r = ydl.extract_info(link, download=False)
            for format in r["formats"]:
                try:
                    str(format["format"])
                except:
                    continue
                if not "dash" in str(format["format"]).lower():
                    try:
                        format["format"]
                        format["filesize"]
                        format["format_id"]
                        format["ext"]
                        format["format_note"]
                    except:
                        continue
                    formats_available.append(
                        {
                            "format": format["format"],
                            "filesize": format["filesize"],
                            "format_id": format["format_id"],
                            "ext": format["ext"],
                            "format_note": format["format_note"],
                            "yturl": link,
                        }
                    )
        return formats_available, link

    async def slider(self, link: str, query_type: int, videoid: Union[bool, str] = None):
        if videoid:
            link = self.base + link
        if "&" in link:
            link = link.split("&")[0]
        a = VideosSearch(link, limit=10)
        result = (await a.next()).get("result")
        title = result[query_type]["title"]
        duration_min = result[query_type]["duration"]
        vidid = result[query_type]["id"]
        thumbnail = result[query_type]["thumbnails"][0]["url"].split("?")[0]
        return title, duration_min, thumbnail, vidid

    async def download(
        self,
        link: str,
        mystic,
        video: Union[bool, str] = None,
        videoid: Union[bool, str] = None,
        songaudio: Union[bool, str] = None,
        songvideo: Union[bool, str] = None,
        format_id: Union[bool, str] = None,
        title: Union[bool, str] = None,
    ) -> str:
        if videoid:
            link = self.base + link
        loop = asyncio.get_running_loop()

        # Shared Options
        common_opts = {
            "geo_bypass": True,
            "nocheckcertificate": True,
            "quiet": True,
            "no_warnings": True,
            "cookiefile": self.cookie_path,
            #"external_downloader": 'aria2c',
            #"external_downloader_args": ['-x', '16', '-s', '16', '-k', '1M'],
        }

        def audio_dl():
            opts = common_opts.copy()
            opts.update({
                "format": "bestaudio/[ext=m4a]",
                "outtmpl": "downloads/%(id)s.%(ext)s",
            })
            x = yt_dlp.YoutubeDL(opts)
            info = x.extract_info(link, False)
            xyz = os.path.join("downloads", f"{info['id']}.{info['ext']}")
            if os.path.exists(xyz):
                return xyz
            x.download([link])
            return xyz

        # --- IMPORTANT: FORCE LOCAL DOWNLOAD FOR VIDEO ---
        # Direct URL streaming causes 403 Forbidden (No Audio/Video), so we download it.
        def video_dl():
            opts = common_opts.copy()
            opts.update({
                # Download Best MP4 available (up to 720p)
                "format": "best[ext=mp4]/bestvideo[ext=mp4]+bestaudio[ext=m4a]/best",
                "outtmpl": "downloads/%(id)s.%(ext)s",
            })
            x = yt_dlp.YoutubeDL(opts)
            info = x.extract_info(link, False)
            xyz = os.path.join("downloads", f"{info['id']}.{info['ext']}")
            if os.path.exists(xyz):
                return xyz
            x.download([link])
            return xyz

        def song_video_dl():
            formats = f"{format_id}+bestaudio/best"
            fpath = f"downloads/{title}"
            opts = common_opts.copy()
            opts.update({
                "format": formats,
                "outtmpl": fpath,
                "prefer_ffmpeg": True,
                "merge_output_format": "mp4",
            })
            x = yt_dlp.YoutubeDL(opts)
            x.download([link])

        def song_audio_dl():
            fpath = f"downloads/{title}.%(ext)s"
            opts = common_opts.copy()
            opts.update({
                "format": format_id,
                "outtmpl": fpath,
                "prefer_ffmpeg": True,
                "postprocessors": [{"key": "FFmpegExtractAudio", "preferredcodec": "mp3", "preferredquality": "320"}],
            })
            x = yt_dlp.YoutubeDL(opts)
            x.download([link])

        try:
            if songvideo:
                await loop.run_in_executor(None, song_video_dl)
                fpath = f"downloads/{title}.mp4"
                return fpath
            elif songaudio:
                await loop.run_in_executor(None, song_audio_dl)
                fpath = f"downloads/{title}.mp3"
                return fpath
            elif video:
                # Always download video locally to avoid "No Video/Audio" issues
                direct = True
                downloaded_file = await loop.run_in_executor(None, video_dl)
            else:
                direct = True
                downloaded_file = await loop.run_in_executor(None, audio_dl)
            
            return downloaded_file, direct
            
        except Exception as e:
            print(f"Download Error: {e}")
            return None, None
